### ISSUE TITLE
视频源语言是中文翻译成别的语言的话会报错

### ISSUE THREAD

**Issue by babysorry** [zhangbo2008/myheygenbeifen#3]
Traceback (most recent call last):
  File "/root/MyHeyGen/translate.py", line 22, in <module>
    translate(
  File "/root/MyHeyGen/translate.py", line 12, in translate
    engine(video_filename, output_filename)
  File "/root/MyHeyGen/core/engine.py", line 126, in __call__
    dst_text = self.text_helper.translate(speaker['text'], src_lang=lang, dst_lang=self.output_language)
  File "/root/MyHeyGen/core/translator.py", line 53, in translate
    src_lang = self.lang_code_map(src_lang)
  File "/root/MyHeyGen/core/translator.py", line 50, in lang_code_map
    return lang_dict[lang_code]
KeyError: 'zh'

**Comment by QRr0w** [comment]
zh to zh-CN
Or modify the list element in translator.py
